theMillionaire/config/routes.rb
Rails.application.routes.draw do


    resources :users
    resource :session, :only => [:create], :controller => 'session'

    match 'logout' => "session#destroy" ,via: :all
    match 'login' => "session#new" , via: :all

    match'setup'=>"setups#show",via: :all

    match'chat'=>"chat#index",via: :all

  end

theMillionaire/app/models/user.rb
class User < ActiveRecord::Base

  validates :user_id, :presence => true, :uniqueness => true
validates :name, :presence => true, :uniqueness => true
validates :password, :presence => true, :uniqueness => true

  before_create :digest_password

  def self.authenticate(name,password)
    where(:name=>name, :password=>Digest::SHA1.hexdigest(password)).first
  end

  private
  def digest_password
    self.password=Digest::SHA1.hexdigest(self.password)
  end
end

theMillionaire/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :find_login_user

   def find_login_user
        @login_user = User.find_by_id(session[:user_id])
        unless @login_user
             redirect_to login_url and return false
        end
end

  private
  def admin_required
    unless @login_user.adm?
      redirect_to_chat_path(@login_user)
    end
end
end

theMillionaire/app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
  end
end

theMillionaire/app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :find_login_user, :only => [:new, :create]

  def new
  end

  def create
     @user_id = params[:user_id]
    @password = params[:password]
    @user= User.authenticate @user_id,@password



    if @user
      session[:user_id] = @user.id
      session[:user_name]=@user.name
      flash[:notice] = "ログインに成功しました"
      if @user.adm
        redirect_to users_path
      else
        redirect_to chat_path #ユーザーのメニュー画面へいく
      end
    else
      @error = "ログインに失敗しました"
        render :action => :new
    end
  end

   def destroy
         reset_session
         redirect_to login_url
     end

end

theMillionaire/app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  before_action :set_setup, only: [:show, :edit, :update, :destroy]
  #データベースから情報を見つけてくる


  # GET /setups/1
  # GET /setups/1.json
  def show
    @setups=session[:user_id]
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setup
      @setup = User.find_by(session[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setup_params
      params.fetch(:setup, {})
    end
end

theMillionaire/app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :find_login_user, :only => [:new, :create]
  #ログインチェックなしで、データ登録と一覧表示
  before_action :set_user, :only=> [:show, :edit, :update, :destroy]
  #ユーザーのデータを取ってきてから表示、編集、更新、削除
  skip_before_filter :login_required, :only=>[:new,:create]
  #ユーザ登録と一覧画面では管理者チェックしない
  before_filter :admin_required, :only=>[:index,:destroy]
  #一覧画面と削除画面は管理者チェックしない
  before_filter :retrieve_user, :only => [:show, :edit, :udpate]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    user_id=params[:id]
    name=params[:name]
  end

  # GET /users/new
  def new
    @user = User.new

  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
     @user = User.new(user_params)


      if @user.save
        session[:user_id] = @user.id
        session[:user_name]=@user.name
        flash[:notice] = "ログインに成功しました"
         redirect_to chat_path
      else
         render :new
      end

  end

   # PATCH/PUT /users/1
   # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    if @user.update_attributes(params[:user])
redirect_to @user, :notice => 'User was successfully updated.'
    else
      render "edit"
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      #params が :user というキーを持ち、
      #params[:user] は :name 及び :email というキーを持つハッシュであること」を検証
      params.require(:user).permit(:user_id, :name, :password)
    end
    def retrieve_user#管理者でなく、一般ユーザーでもない場合、ユーザー一覧へ
    unless @login_user.adm? or @login_user.id == @user.id
        redirect_to user_path(@login_user)
      end
    end

theMillionaire/app/controllers/websocket_chat_controller.rb
#WebsocketRails::BaseControllerを継承
 class WebsocketChatController < WebsocketRails::BaseController
   def message_recieve
      # クライアントからのメッセージを取得
     recieve_message = message()

     # websocket_chatイベントで接続しているクライアントにブロードキャスト
     broadcast_message(:websocket_chat, recieve_message)
  end

end

theMillionaire/app/helpers/chat_helper.rb
module ChatHelper
end

theMillionaire/app/views/chat/index.html.erb
<!-- RailsからJS側へログインユーザの名前を渡す用div うまいやり方が思いつかなかった -->
<div>
  ようこそ<span id="login_user"><%= session[:user_name] %></span>さん
</div>
<!-- 現在ゲームルームに接続しているユーザ名を全て表示する -->
<div>
  listener:<span id="listener"></span>
</div>

<!-- コメントフォーム -->
<input id="comment" type="text">
<input id="send" type="button" value="send">
<input id="ready" type="button" value="準備完了"><br>
<input id="trushhand" type="button" value="出す">
<input id="pass" type="button" value="パス">
<!-- ゲームステージがここに描画される-->
<div id="enchant-stage" style="background-color:#006432;">
</div>

<!--　ゲームスクリプト -->
<script>
  /*ゲーム画面の定義*/
  enchant();//enchant.jsの有効化
  var core = new Core(640, 480);

  /******************ここからサーバ通信メソッド********************/
  /*ゲームの「新しくログインした奴がいた場合画面の名前欄を更新」って処理を
  実現しなければならないので、なかなかにコードが頭悪い*/

  //websocketサーバへの接続
  var ws = new WebSocket("ws://192.168.100.33:3001/");
  //自分のログインユーザ名の取得
  var ownname=document.getElementById("login_user").textContent;
  var ownturn=1;//自分のターン
  var fieldturn=1;//「誰の番か？」
  var num_login=1;

  //各ログインユーザのテキスト。0に自分の名前が入り、1からは他の人間が入る
  //クライアントごとで0以外のindexに入る名前の順番は一意とは限らないものとする
  var nametext=[];
  //名前を表示する座標。
  //「平民」などの身分を表示する座標はこれのyに30足すものとする
  var nameposition_x=[95,530,350,28];
  var nameposition_y=[395,280,20,160];
  var imagepaths=[];//手札配列　jokerなしは13、jokerありは14
  var handimage=[];//手札の画像オブジェクトの格納される配列
  var my_hands=13;
  var suit=["club","spade","dia","heart"]

  var tmp_cardpath="";

  var trush=new Array(4);
  var trushhands="";//自身が選択した捨て場に捨てるカード

  var fieldcard="back_0";//場のカード
  var fieldcardnum=0;//場のカードの枚数
  var revolution_flag=0;//場の革命状態フラグ(0:通常,1:革命)

  var isTouch=false;
  var touchX=null;
  var touchY=null;



  for(var suit_index=0;suit_index<4;suit_index++){
    for(var num_index=0;num_index<13;num_index++){
      console.log(document.getElementById("imagepath_"+suit[suit_index]+"_"+(num_index+1)).value);
      core.preload(document.getElementById("imagepath_"+suit[suit_index]+"_"+(num_index+1)).value);
    }
  }
  core.preload(document.getElementById("imagepath_joker_14_1").value);
  core.preload(document.getElementById("imagepath_joker_14_2").value);
  core.preload(document.getElementById("imagepath_back_0").value);
  core.preload(document.getElementById("clearfield").value);

  //通信確立時に行われる処理。ログインユーザのuser_nameを自動的にサーバに送信し
  //現在何人のユーザがアクティブなのかをサーバからユーザに返してもらう
  ws.onopen=function(){
    ws.send("messagetype*username*value*"+ownname);//自分の名前の送信
    ws.send("messagetype*Allusername*value*open");//全listenの取得
  };

  // メッセージ受信時の処理
  //この部分で「新しくログインしたユーザがいれば名前表示欄を更新する」処理を入れてる
  ws.onmessage = function(event){
    //受信したレスポンスメッセージを区切り文字で分割し、解読の足がかりにする
    var array_of_message=event.data.split("*");

    //usernameメッセージの場合、listener領域に自分の名前をpush
    if(array_of_message[1]=="username" && document.getElementById("listener").textContent.match(ownname)==null)
      document.getElementById("listener").append(ownname);

    //commentメソッドの場合コメント表示領域にコメントをpush
    else if(array_of_message[1]=="comment")
      document.getElementById("chat_area").append(array_of_message[3]);

    //Allusernameメソッドの場合listener領域に全listenユーザを表示
    else if(array_of_message[1]=="Allusername"){
      document.getElementById("listener").innerHTML=array_of_message[3];

      //ゲーム画面の「新しくログインしたユーザがいれば名前表示欄を更新する」処理用に
      //listener領域の文字列を,でsplitし、全ユーザの配列として生成
      var loginusers=document.getElementById("listener").textContent.split(",");

      //他のユーザが入ってくるたびに「他のユーザ名格納配列」のindexをリセットする
      num_login=1;
      var absolute=0;
      //全listenユーザに対して、名前の表示位置を決定するfor
      for(var index=0;index<loginusers.length;index++){

        //自分の名前を引っ張ってきた場合一番手前の位置に名前を書く
        if(document.getElementById("listener").textContent.split(",")[index]==ownname){
          nametext[0]=new Label(ownname);//自分の名前を格納
          nametext[0].x=nameposition_x[0];//x位置決定(下名前枠)
          nametext[0].y=nameposition_y[0];//y位置決定(下名前枠)
          core.rootScene.addChild(nametext[0]);//名前の描画
        }

        //他の人間の名前を引っ張ってきたら右上左のどこかの枠に名前を書く
        else{
          //他のユーザの名前を格納
          absolute=index-document.getElementById("listener").textContent.split(",").indexOf(ownname);
          if(absolute<0)//自分に対する他のプレイヤーのテーブル位置の決定
            absolute+=4;
          nametext[absolute]=new Label(document.getElementById("listener").textContent.split(",")[index]);
          nametext[absolute].x=nameposition_x[absolute];//x位置決定(indexの順に右、上、左に奴)
          nametext[absolute].y=nameposition_y[absolute];//y位置決定(indexの順に右、上、左の奴)
          core.rootScene.addChild(nametext[absolute]);//名前の描画
          num_login++;//「他のユーザ名格納配列」のindexを1つ進める
        }


      }//for(var index=0;index<loginusers.length;index++)終了

    }//Allusername終了

    else if(array_of_message[1]=="DeckCreate"){
      console.log("deckcreate");

      for(var i=0;i<13;i++){

        imagepaths[i]=array_of_message[3].split(",")[i];
        handimage[i] = new Sprite(32,64);//手札の代入
        console.log(array_of_message[3].split(",")[i]);
        handimage[i].image=core.assets[document.getElementById("imagepath_"+array_of_message[3].split(",")[i]).value];
        handimage[i].x=200+i*32;
        handimage[i].y=385;
        core.rootScene.addChild(handimage[i]);
      }
      //otherhands = new Sprite(32,64);//他者手札の代入
      //console.log(array_of_message[3].split(",").sort());
      //otherhands.image=core.assets[document.getElementById("imagepath_back").value];
      //otherhands.x=500;
      //otherhands.y=200;
      //core.rootScene.addChild(otherhands);


    }//DeckCreate　終了

    else if(array_of_message[1]=="GameStart"){
      ownturn=array_of_message[3];
      fieldturn=0;

      console.log("あなたは"+ownturn+"番目です");

    }

    else if(array_of_message[1]=="InformField"){
      fieldcard=array_of_message[3];
      fieldturn=array_of_message[5];
      console.log(fieldturn+"のターン");
      console.log("fieldcard:"+fieldcard.split("_"));
      fieldcardnum=array_of_message[3].split("_")[0].split(",").length-1;
      console.log("fieldcard="+fieldcard);
      console.log("fieldcardnum:"+fieldcardnum);
      if(revolution_flag!=Number(array_of_message[7])){
        revolution_flag=Number(array_of_message[7]);
        if(Number(array_of_message[7])==1){
          document.getElementById("chat_area").innerHTML+="<br>messagetype*comment*value*[革命勃発！]3>>K>>2";
        }
        else if(Number(array_of_message[7])==0){
          document.getElementById("chat_area").innerHTML+="<br>messagetype*comment*value*[革命鎮圧！]3<<K<<2";
        }
      }
      revolution_flag=Number(array_of_message[7]);
      console.log(array_of_message[3]+"が出されました:"+fieldcardnum+"枚");
      trushhands="";

      if(fieldcard=="back_0"){
        //core.rootScene.removeChild(resetfield);
        var resetfield=new Sprite(120,120);
        resetfield.image=core.assets[document.getElementById("clearfield").value];
        resetfield.x=280;
        resetfield.y=180;
        core.rootScene.addChild(resetfield);
        fieldcard="back_0";
        trushhands="";
        fieldcardnum=0;
      }

      //ゲーム画面をクリックした場合の処理。「カードの領域」をクリックした場合
      //「カードを選択したもの」と処理する
      if(ownturn==fieldturn){
        document.getElementById("chat_area").innerHTML="[message]あなたのターンです";
      }
      else{
        document.getElementById("chat_area").innerHTML="[message]"+document.getElementById("listener").textContent.split(",")[fieldturn]+"のターンです";
      }
      for(var i=0;i<array_of_message[3].split("_")[0].split(",").length-1;i++){
      core.rootScene.removeChild(trush[i]);
      trush[i]= new Sprite(32,64);
      trush[i].image=core.assets[document.getElementById("imagepath_"+array_of_message[3].split("_")[0].split(",")[i]+"_"+array_of_message[3].split("_")[1]).value];
      trush[i].x=300+i*10;
      trush[i].y=200;
      core.rootScene.addChild(trush[i]);
    }
      //core.rootScene.removeChild(handimage[selectedcard]);
      //ws.send("messagetype*SubmitCard*value*"+imagepaths[selectedcard]+"*player*"+ownname+"*hands*"+my_hands);//全listenの取得
    }
    isTouch=false;

  };//ws.onmessage終了
  document.getElementById("enchant-stage").addEventListener("click",function(e){
      if(ownturn==fieldturn){
        isTouch=true;
        touchX=(e.pageX-(window.innerWidth-640)/2-11);//クリックしたゲームウィンドウのx座標
        touchY=(e.pageY-(window.innerHeight-480)/2-6);//クリックしたゲームウィンドウのy座標
        console.log("[x]:"+e.pageX+"[y]"+e.pageY);
        console.log("gamewidth="+(touchX));
        console.log("gameheight="+(touchY));
        console.log("imagepaths:"+imagepaths);

        var selectedcard=parseInt((touchX-200)/32);//クリック座標から割り出した、クリック手札座標
        if(selectedcard>=0 && selectedcard<=12 && touchY>=385 && touchY<=449){
          //選択したカードが、捨て場のカードに対し大きい数なら選択可能
          console.log("fieldcardnum:"+fieldcardnum+"trushhands:"+trushhands.split(",").length-1);
          console.log("fieldcard:"+fieldcard);
          console.log("selectedcard="+imagepaths[selectedcard]);
          if(Number(fieldcard.split("_")[1])<Number(imagepaths[selectedcard].split("_")[1]) && imagepaths[selectedcard]!="back_0"){
            if((Number(imagepaths[selectedcard].split("_")[1])==Number(trushhands.split(",")[0].split("_")[1])) && fieldcardnum>=Number(trushhands.split(",").length-1) || fieldcardnum==0 || Number(trushhands.split(",").length)==1){
              if(handimage[selectedcard].y==385 && fieldcardnum!=Number(trushhands.split(",").length-1) || fieldcardnum==0){
                trushhands+=(imagepaths[selectedcard]+",");
                handimage[selectedcard].y=355;
                core.rootScene.addChild(handimage[selectedcard]);
              }
              else if(handimage[selectedcard].y==355){
                trushhands=trushhands.replace(imagepaths[selectedcard]+",","") ;
                handimage[selectedcard].y=385;
                core.rootScene.addChild(handimage[selectedcard]);
              }
              console.log("選択カード:"+trushhands);
            }
          }

            /*
          my_hands-=1;
          var trush= new Sprite(32,64);
          trush.image=core.assets[document.getElementById("imagepath_"+imagepaths[selectedcard]).value];
          trush.x=300;
          trush.y=200;
          core.rootScene.addChild(trush);
          core.rootScene.removeChild(handimage[selectedcard]);
          ws.send("messagetype*SubmitCard*value*"+imagepaths[selectedcard]+"*player*"+ownname+"*hands*"+my_hands);//全listenの取得
          */
        }
      }
    });


  // コメント送信ボタンを押した時の処理
  document.getElementById("send").onclick = function(){
    //コメント領域の入力値の取得
    var comment = document.getElementById("comment").value;
    //commentリクエストメッセージ
    var send_message="messagetype*comment*value*"+comment;
    //commentリクエストメッセージを送信。他のlistenerへコメントを同期してもらう
    ws.send(send_message);
  };

  //準備完了ボタンを押した時、シャッフルされた山札から
  //手札が順次配布される
  document.getElementById("ready").onclick = function(){
    //コメント領域の入力値の取得
    //var comment = document.getElementById("comment").value;
    //commentリクエストメッセージ
    //var send_message="messagetype*comment*value*"+comment;
    //commentリクエストメッセージを送信。他のlistenerへコメントを同期してもらう
    if(num_login-1==4)
    ws.send("messagetype*DeckShuffle*value*"+ownname);
  };

  //パスを選択した場合の処理
  document.getElementById("pass").onclick = function(){
    ws.send("messagetype*Pass*value*"+ownname);
  };

  //「出す」を選択した場合の処理
  document.getElementById("trushhand").onclick = function(){
    console.log(my_hands);
    if((trushhands.split(",").length-1==fieldcardnum || fieldcardnum==0) && ownturn==fieldturn){
      my_hands=my_hands-trushhands.split(",").length+1;
      console.log(my_hands);
      for(var i=0;i<trushhands.split(",").length-1;i++){
        core.rootScene.removeChild(handimage[imagepaths.indexOf(trushhands.split(",")[i])]);
        imagepaths[imagepaths.indexOf(trushhands.split(",")[i])]="back_0";
      }
      console.log("messagetype*SubmitCard*value*"+trushhands+"*player*"+ownname+"*hands*"+my_hands);
      if(my_hands==0){
        document.getElementById("listener").innerHTML+="<br>[あがり！]";
      }
      ws.send("messagetype*SubmitCard*value*"+trushhands+"*player*"+ownname+"*hands*"+my_hands);
  }
  };

  core.start();//ゲーム画面を実際にブラウザへ描画する
</script>

theMillionaire/app/views/session/new.html.erb
<h1>The Millionaire</h1>

<% if @error %>
 <%= @error %><br />
<% end %>

<%= form_tag session_url do %>
  <%= label :user_id, '' %>
  <%= text_field_tag :user_id, @user_id ,:placeholder => "Enter your ID" %><br />
  <%= label :password, '' %>
  <%= password_field_tag :password, "" ,:placeholder => "Enter your Password" %><br />
  <%= submit_tag "Login" %><br />
<% end %>
アカウントをお持ちでない方は
<%= link_to "こちら", new_user_url %>

theMillionaire/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

theMillionaire/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table style="border-style:outset;border-width:12px;">
  <thead>

    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><a href="http://192.168.100.33:3000/users/<%=user.user_id%>"><%= user.user_id %></a></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'GameStart', chat_path %>

theMillionaire/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

theMillionaire/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<%=session[:user_id]%>